apiversion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
    - port: 80
     taregetport: 80
  type: LoadBalancer

 ---

apiversion: v1
kind: service
metadata:
  name: mysql-connection
  spec:
 ports:
  - port: 3306
 selector:
  app: mysql
  clusterIP: None